"""Add rule field to Role model

Revision ID: a937affbbaa5
Revises: e616b2d21d41
Create Date: 2024-05-31 23:50:46.036487

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a937affbbaa5'
down_revision: Union[str, None] = 'e616b2d21d41'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('tbl_role', sa.Column('rule', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tbl_role', 'rule')
    # ### end Alembic commands ###
